[code]
editor = 'nvim'
lang = 'cpp'
edit_code_marker = false
start_marker = ""
end_marker = ""
comment_problem_desc = true 
comment_leading = "//"
test = true
inject_before = ["#include<bits/stdc++.h>", "using namespace std;\n"]

[cookies]
csrf = 'almrTTGfk9XDuQf5jq9sf4M92dEZYENV3dou3AkvtGEPVeWK59Ui1FyBya1BklLi'
session = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNjE4MzA3OSIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImQ0MmYyYjk5MzQ2M2ZhYWM3OTg4NDRiY2FlNDYyMTU3ZjA3YmQyMjQ4YzI4MDRlMjU0Mzg0ZDQwOTMzMzU3OGIiLCJzZXNzaW9uX3V1aWQiOiI0NWQ2MGQwYiIsImlkIjo2MTgzMDc5LCJlbWFpbCI6Imt1bWFyLmFycGl0NzdAeWFob28uY29tIiwidXNlcm5hbWUiOiJrdW1hcnBpdCIsInVzZXJfc2x1ZyI6Imt1bWFycGl0IiwiYXZhdGFyIjoiaHR0cHM6Ly9hc3NldHMubGVldGNvZGUuY29tL3VzZXJzL2F2YXRhcnMvYXZhdGFyXzE2NDk4MzA1MzgucG5nIiwicmVmcmVzaGVkX2F0IjoxNzQwMTk0MDM4LCJpcCI6IjEyOC4xODkuOTAuNzAiLCJpZGVudGl0eSI6ImIzM2RjMzQ1ODk1Yjc3ZGQ0NmFkNzhhZDdkNDQyODBhIiwiZGV2aWNlX3dpdGhfaXAiOlsiZjkzNzMyOGEyMzg3ZTFiZDE2MjgxMDA5ZjdhNzA1M2MiLCIxMjguMTg5LjkwLjcwIl19.WJprmYanN_UzrHn1gPsJphWqWA3sNsTcy5KjODhbm70'
site = "leetcode.com"

[storage]
cache = 'Problems'
code = 'code'
root = '~/.leetcode'
scripts = 'scripts'

